image: docker:git

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: 'tcp://localhost:2375'
  DOCKER_DRIVER: 'overlay'
  DOCKER_IMAGE_NAME: 'localbeach-nginx-proxy'

build-tagged:
  stage: build
  only:
    - tags
  script:
    - docker login -u _json_key -p "$CI_CONTAINER_REGISTRY_TOKEN" https://eu.gcr.io
    - docker build -t eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID} .
    - docker push eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID}
    - docker tag eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID} eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID} eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:latest
    - docker push eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:latest

    - docker login -u "$DOCKER_IO_REGISTRY_USER" -p "$DOCKER_IO_REGISTRY_PASSWORD" $DOCKER_IO_REGISTRY
    - docker tag eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID} docker.io/flownative/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID}
    - docker push docker.io/flownative/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID}
    - docker tag eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID} docker.io/flownative/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push docker.io/flownative/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag eu.gcr.io/flownative-beach/${DOCKER_IMAGE_NAME}:build-${CI_JOB_ID} docker.io/flownative/${DOCKER_IMAGE_NAME}:latest
    - docker push docker.io/flownative/${DOCKER_IMAGE_NAME}:latest
