name: Build Docker images
on:
  repository_dispatch:
    types: [nginx-images-built]
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 100

      - name: Determine latest version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - run: |
          sudo chmod -R ugo+rwX . && shopt -s dotglob && rm -rf *

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest_version.outputs.tag }}
          fetch-depth: 100
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: flownative/docker-localbeach-nginx-proxy/localbeach-nginx-proxy:${{ steps.latest_version.outputs.value }}

      - name: Tag semver releases
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.build_image.outputs.image_tag }}
          tag_latest: 'no'

          source_image_name: docker.pkg.github.com/flownative/docker-localbeach-nginx-proxy/localbeach-nginx-proxy
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: docker.pkg.github.com/flownative/docker-localbeach-nginx-proxy/localbeach-nginx-proxy
          target_registry_username: github
          target_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          target_registry_endpoint: https://docker.pkg.github.com/v2/

      - name: Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          event-type: image-built
          client-payload: '{"image_name": "${{ steps.build_image.outputs.image_name }}", "image_tag": "${{ steps.build_image.outputs.image_tag }}"}'
